apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatops-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "chatops.redis.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chatops.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatops.redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          command:
            - redis-server
            - --save
            - "60"
            - "1"
            - --loglevel
            - warning
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
