apiVersion: v1
kind: Service
metadata:
  name: chatops-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "chatops.frontend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "chatops.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
