apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatops-postgres-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "chatops.postgres.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep   # Don't delete data on helm uninstall!
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
